apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synthetic-monitor-config
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: synthetic-monitor-config
  data:
    - secretKey: config.json
      remoteRef:
        key: secret/data/synthetics/config